---
spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: postgres
    password: postgres

  batch:
    initialize-schema: always
    job:
      enabled: false



  main:
    allow-bean-definition-overriding: true
